services:
  - type: web
    name: backend-fastapi-aiagent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: npm run start
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
